export default [
   {
      id: 65465461,
      name: "Dharma amasha",
      course: 'MPC',
      location: "Marredpally",
      SSCResult: 80,
      status: "Accepted",  
   },
   {
      id: 65465561,
      name: "Nothing Hello",
      course: 'BSA',
      location: "Yapral",
      SSCResult: 70,
      status: "Pending",  
   },
   {
      id: 65469561,
      name: "Nothing Hello 2",
      course: 'BSD',
      location: "Tirumalgiri",
      SSCResult: 80,
      status: "Rejected",  
   },
   {
      id: 65409561,
      name: "Nothing Hello 2",
      course: 'BSD',
      location: "Tirumalgiri",
      SSCResult: 80,
      status: "Rejected",  
   },
   {
      id: 69409561,
      name: "Nothing Hello 2",
      course: 'BSD',
      location: "Tirumalgiri",
      SSCResult: 80,
      status: "Rejected",  
   },
   {
      id: 69419561,
      name: "Nothing Hello 2",
      course: 'BSD',
      location: "Tirumalgiri",
      SSCResult: 80,
      status: "Rejected",  
   },
   {
      id: 67419561,
      name: "Nothing Hello 2",
      course: 'BSD',
      location: "Tirumalgiri",
      SSCResult: 80,
      status: "Rejected",  
   },
];
